" Enable Pathogen
execute pathogen#infect()
syntax on
color dracula
filetype plugin indent on


" line numbers by default
set number
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab


" show airline tabs
let g:airline#extensions#tabline#enabled = 1


" NERDTree configuration

" autostart if no files specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
" toggle with Ctrl+n
map <C-n> :NERDTreeToggle<CR>
" close vim if NERDTree is only window left
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif