export LC_ALL=en_US.UTF-8

# Print a random, hopefully interesting, adage.
if (( $+commands[fortune] )); then
  if [[ -t 0 || -t 1 ]]; then
    print
    fortune -s
    print
  fi
fi


# main entry point to the slimzsh framework
source $HOME/.slimzsh/slim.zsh


# added by travis gem
[ -f /Users/aobrien/.travis/travis.sh ] && source /Users/aobrien/.travis/travis.sh
