# Print a random, hopefully interesting, adage.
if (( $+commands[fortune] )); then
  if [[ -t 0 || -t 1 ]]; then
    print
    fortune -s
    print
  fi
fi


# main entry point to the slimzsh framework
source $HOME/.slimzsh/slim.zsh
